name: mezgebe_sibhat
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.5
  http: ^1.5.0
  shared_preferences: ^2.5.3
  get_it: ^9.0.5
  image_picker: ^1.2.0
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  dartz: ^0.10.1
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter_launcher_icons:
  android: true
  ios: true
  adaptive_icon_background: "assets/icon.png"
  adaptive_icon_foreground: "assets/icon.png"
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
